### ISSUE TITLE
Typo in Corollary 2.3 in Theorems 

### ISSUE THREAD

**Issue by RSaiNithish** [Deepam-Rai/Notes#1]
It should be G2 and not G1
issue with $$\large \sum_{v\in V(G_1)}{deg(v_i)} + 2l = 2m$$
since $\sum_{v\in V(G_1)}{deg(v_i)}=2l$ 
then,
$$2l  + \large \sum_{v\in V(G_2)}{deg(v_i)}  = 2m$$

**Comment by Deepam-Rai** [comment]
Thank bro, its rectified in new commit. @RSaiNithish
